var age = 25;
age = true;
console.log(age);
age = 'Mindula';
console.log(age);
age = { name: 'Dilthushan' };
console.log(age);
var all = [];
all.push(5);
all.push('Shan');
all.push(false);
console.log(all);
